#!/bin/bash

DESKTOP_DIR="$HOME/Desktop/"


for FILE in "$@"; do
    BASENAME=$(basename "$FILE")
    NAME="${BASENAME%.*}"

    ABS_PATH=$(realpath "$FILE")
    DIR=$(dirname "$FILE")

    
    [[ $ABS_PATH =~ ".png" ]] && echo "hi

    
done
